# Contents List

## 01. Importing Libraries
## 02. Paths
## 03. Importing Data
## 04. Data Manipulation
## 05. Grouping Data with pandas
## 06. Aggregating Data
## 07. Aggregating Data with transform()
## 08. Deriving Columns with loc()
## 09. Task 4.8

# 01. Importing libraries

In [2]:
#Import libraries
import pandas as pd
import numpy as np
import os

# 2. Paths

In [4]:
#Creating a path varaible - Shortcut for Importing Data Files
path = r'/Users/aya/Desktop/DataAnalytics/Data-Immersion/Achievement-4/Instacart-Basket-Analysis'

In [5]:
path

'/Users/aya/Desktop/DataAnalytics/Data-Immersion/Achievement-4/Instacart-Basket-Analysis'

# 03. Importing Data

In [7]:
#Import ords_prods_merge_Deriving_Variables Dataset
ords_prods_merge = pd.read_pickle(os.path.join(path, '02-Data', 'Prepared-Data', 'ords_prods_merge_Deriving_Variables.pkl'))

In [8]:
#Checking the dataframe
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders

# 04. Data Manipulation

In [10]:
#Subsetting the 'ords_prods_merge' dataframe and assign it to 'df' dataframe
df = ords_prods_merge[:1000000]

In [11]:
#Checking the the 'df' dataframe dimension
df.shape

(1000000, 18)

In [12]:
#Checking the the 'df' dataframe
df.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders

# 05. Grouping Data with pandas

In [14]:
#Grouping the 'df' dataframe by 'product_name'
df.groupby('product_name')

# 06. Aggregating Data

In [16]:
#Single Aggregation (mean)
#Aggregate the 'order_number' column in the 'df' dataframe grouped by 'department_id'
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [17]:
#Multiple Aggregations (mean', 'min', 'max)
#Aggregate the 'order_number' column in the 'df' dataframe grouped by 'department_id' 
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.447411   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.803851   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

# 07. Aggregating Data with transform()

In [19]:
#Creating a new column named 'max_order' in the 'df' dataframe, Grouped by 'user_id' column &
#Applying the transform function on the 'order_number' column to Aggregate by Max. 
df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/62/xltcnc5n7d97j6t5ql_87vym0000gn/T/ipykernel_14577/3541529635.py:3: FutureWarning: The provided callable <function max at 0x1060f3060> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)
/var/folders/62/xltcnc5n7d97j6t5ql_87vym0000gn/T/ipykernel_14577/3541529635.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

In [20]:
#Checking the 'df' dataframe
df.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,16
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,18
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,18

In [21]:
#Sorting the dataframe by 'user_id' to confirm the number of orders with the maximum order
df.sort_values(by=['user_id'], ascending=[True]).head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order
92369,196,Soda,77,7,9.0,2398795,1,2,3,7,15.0,1,1,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
92375,196,Soda,77,7,9.0,3108588,1,8,1,14,14.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
92370,196,Soda,77,7,9.0,473747,1,3,3,12,21.0,1,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
92374,196,Soda,77,7,9.0,550135,1,7,1,9,20.0,1,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
92373,196,Soda,77,7,9.0,3367565,1,6,2,7,19.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494265,1005,China Green Tips Green Tea,94,7,4.7,1149132,27,21,2,11,8.0,7,1,both,Low-range product,Regularly busy,Regular days,Most orders,81
494264,1005,China Green Tips Green Tea,94,7,4.7,2705360,27,16,2,16,8.0,9,1,both,Low-range product,Regularly busy,Regular days,Most orders,81
494263,1005,China Green Tips Green Tea,94,7,4.7,1406911,27,14,3,9,8.0,8,0,both,Low-range product,Regularly busy,Slowest days,Most orders,81
656370,1323,Vanilla Bean Natural Lowfat Yogurt,120,16,11.1,1603399,27,38,2,16,1.0,8,0,both,Mid-range product,Regularly busy,Regular days,Most orders,81
985637,2067,Plus Cranberry Almond + Antioxidants with Maca...,3,19,5.5,2005447,27,37,1,10,3.0,4,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,81

In [22]:
#Chckeing the 'df' dataframe
df.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,8
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid-range product,Regularly busy,Regular days,Most orders,23
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,16
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid-range product,Regularly busy,Regular days,Most orders,21

In [23]:
#Changing the output display - to be able to view the desired bmuber of rows. 
pd.options.display.max_rows = None

In [24]:
#Chckeing the 'df' dataframe Again
df.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,16
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,18
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,18
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,6
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,41
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,41
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Regular days,Most orders,41
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,9
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,18,1,both,Mid-range product,Regularly busy,Regular days,Average orders,9
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,12,1,both,Mid-range product,Regularly busy,Regular days,Average orders,9
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Regular days,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,8.0,7,1,both,Mid-range product,Regularly busy,Regular days,Fewest orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,6.0,6,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,28.0,6,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,7.0,10,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,7.0,3,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,0.0,5,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,7.0,11,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,7.0,11,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,7.0,5,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,7.0,15,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,3.0,4,1,both,Mid-range product,Least busy,Slowest days,Average orders,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,16.0,6,1,both,Mid-range product,Regularly busy,Regular days,Average orders,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,5.0,1,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,6.0,1,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,NaN,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,21.0,2,1,both,Mid-range product,Regularly busy,Regular days,Most orders,3
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,2.0,3,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,NaN,1,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,9
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,18.0,6,1,both,Mid-range product,Busiest day,Busiest days,Most orders,9
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,8.0,3,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,9
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,30.0,10,1,both,Mid-range product,Busiest day,Busiest days,Average orders,9
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,25.0,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,9
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,NaN,12,0,both,Mid-range product,Busiest day,Busiest days,Most orders,1
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,9.0,10,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,21
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,10.0,5,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,24
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,7.0,11,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,NaN,8,0,both,Mid-range product,Regularly busy,Regular days,Average orders,4
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,30.0,7,0,both,Mid-range product,Regularly busy,Regular days,Most orders,4
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,NaN,2,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,1
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,7.0,8,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,40
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,7.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,40
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,7.0,6,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,40
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,5.0,3,1,both,Mid-range product,Regularly busy,Regular days,Most orders,40
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,4.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,40
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,8.0,1,0,both,Mid-range product,Regularly busy,Regular days,Average orders,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,30.0,2,0,both,Mid-range product,Busiest day,Busiest days,Average orders,2
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,NaN,9,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,29.0,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,12.0,7,0,both,Mid-range product,Busiest day,Busiest days,Most orders,6
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,NaN,11,0,both,Mid-range product,Least busy,Slowest days,Most orders,1
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,4.0,6,0,both,Mid-range product,Regularly busy,Regular days,Fewest orders,5
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,5.0,5,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,5.0,6,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,13.0,3,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,10.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,30
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,6.0,1,1,both,Mid-range product,Busiest day,Busiest days,Fewest orders,30
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,9.0,1,1,both,Mid-range product,Regularly busy,Regular days,Fewest orders,30
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,6.0,2,1,both,Mid-range product,Regularly busy,Regular days,Most orders,30
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,8.0,2,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,30
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,1.0,13,0,both,Mid-range product,Least busy,Slowest days,Most orders,98
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,7.0,2,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,35
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,21.0,2,0,both,Mid-range product,Least busy,Slowest days,Most orders,8
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,30.0,2,0,both,Mid-range product,Busiest day,Busiest days,Most orders,3
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,30.0,1,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,NaN,11,0,both,Mid-range product,Busiest day,Busiest days,Average orders,1
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,30.0,3,0,both,Mid-range product,Busiest day,Busiest days,Average orders,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,8.0,2,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,7.0,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,14.0,2,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,28.0,1,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,16.0,4,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,1.0,1,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,14.0,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,7.0,2,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,8.0,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,16.0,7,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,8.0,16,0,both,Mid-range product,Least busy,Slowest days,Average orders,17
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,14.0,5,0,both,Mid-range product,Least busy,Slowest days,Average orders,8
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,NaN,2,0,both,Mid-range product,Busiest day,Busiest days,Most orders,1
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,8.0,8,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,14.0,15,0,both,Mid-range product,Regularly busy,Regular days,Most orders,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,14.0,9,1,both,Mid-range product,Regularly busy,Regular days,Most orders,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,10.0,1,0,both,Mid-range product,Busiest day,Busiest days,Average orders,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,14.0,4,1,both,Mid-range product,Busiest day,Busiest days,Average orders,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,4.0,2,1,both,Mid-range product,Regularly busy,Regular days,Most orders,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,8
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid-range product,Regularly busy,Regular days,Most orders,23
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,16
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid-range product,Regularly busy,Regular days,Most orders,21

# 08. Deriving Columns with loc()
##### Creating falgs - Assinging loyalty status in the new column named 'loyalty_flag' based on the rows of the 'max_order' column in the 'ords_prods_merge' dataframe

In [26]:
#Assinging loyalty status - (> 40)  then 'Loyal customer'
df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

/var/folders/62/xltcnc5n7d97j6t5ql_87vym0000gn/T/ipykernel_14577/3336362628.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [27]:
#Assinging loyalty status -  (<= 40 &  > 10) then 'Regular customer'
df.loc[(df['max_order'] <= 40) & (df['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [28]:
#Assinging loyalty status - (<= 10) then 'New customer'
df.loc[df['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [29]:
#Checking the new column 
df['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    473070
Loyal customer      287917
New customer        239013
Name: count, dtype: int64

In [30]:
#Checking the a list of columns within a the dataframe
df[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494      New customer             6
15     1494      New customer             7
16     1494      New customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010      New customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006  Regular customer             2
50     4006  Regular customer             3
51     4006  Regular customer             5
52     4006  Regular customer             9
53     4006  Regular customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845      New customer             6
59     6866      New customer             1

# Task 4.8

In [32]:
#Checking the ords_prods_merge dataframe
ords_prods_merge.shape

(32404859, 18)

In [33]:
##Aggregate the 'order_number' column in the ords_prods_merge dataframe grouped by 'department_id'
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

# Observation 2. & 3.
###### Average orders for each department (There are 21 departments)
###### The range of means between different departments is between ~15 to ~22.

In [35]:
#Creating a new column named 'max_order' in the 'ords_prods_merge' dataframe, Grouped by 'user_id' column &
#Applying the transform function on the 'order_number' column to Aggregate by Max. 
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/62/xltcnc5n7d97j6t5ql_87vym0000gn/T/ipykernel_14577/2351130679.py:3: FutureWarning: The provided callable <function max at 0x1060f3060> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [36]:
#Checking the dataframe
ords_prods_merge.shape

(32404859, 19)

In [37]:
#Checking the dataframe
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3

In [38]:
#Deriving Columns
#Assinging loyalty status - (> 40)  then 'Loyal customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [39]:
#Assinging loyalty status -  (<= 40 &  > 10) then 'Regular customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [40]:
#Assinging loyalty status - (<= 10) then 'New customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [41]:
#Checking the new column 
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [42]:
#Checking the a list of columns within a the dataframe
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010  Regular customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006    Loyal customer             2
50     4006    Loyal customer             3
51     4006    Loyal customer             5
52     4006    Loyal customer             9
53     4006    Loyal customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845  Regular customer             6
59     6866      New customer             1

# Observation 4.
#### The entrier dataframe ords_prods_merge:
#### Groued by 'user_id'
#### Aggregated the 'order_number' and transform(max)
#### Assigned flags using the loc()

In [44]:
#Checking the dataframe 'ords_prods_merge'
ords_prods_merge.head(20)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12,Regular customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20,Regular customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20,Regular customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,10,New customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43,Loyal customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43,Loyal customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Regular days,Most orders,43,Loyal customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13,Regular customer
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,18,1,both,Mid-range product,Regularly busy,Regular days,Average orders,13,Regular customer
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,12,1,both,Mid-range product,Regularly busy,Regular days,Average orders,13,Regular customer
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Regular days,Fewest orders,28,Regular customer
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28,Regular customer
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer

In [45]:
#Aggregate the 'prices' column in the 'ords_prods_merge' dataframe grouped by 'loyalty_flag' 
#The basic statsitcs of the product prices of each loyalty category
ords_prods_merge.groupby(['loyalty_flag']).agg({'prices':['mean', 'min', 'max']})

                    prices
                      mean  min   max
loyalty_flag
Loyal customer    7.773487  1.0  25.0
New customer      7.801077  1.0  25.0
Regular customer  7.798145  1.0  25.0

# Observation 5. 
##### The prices of products purchased by loyal customers are  comparable or very close to those purchased by regular or new customers.

In [47]:
#Apply the transform () funtion on the 'prices' column to generate the average spent amount for each user
#Assign the results in a new column names 'Avg_spending'
ords_prods_merge['Avg_spending'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

/var/folders/62/xltcnc5n7d97j6t5ql_87vym0000gn/T/ipykernel_14577/4152911572.py:3: FutureWarning: The provided callable <function mean at 0x1060f3a60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['Avg_spending'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [48]:
#Checkign the dataframe
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,Avg_spending
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414

In [49]:
#Deriving anew column named 'spending_flag', with loc()
#Setting up criteria - High spender >= 10
ords_prods_merge.loc[ords_prods_merge['Avg_spending'] >= 10, 'spending_flag'] = 'High spender'

In [50]:
#Deriving anew column named 'spending_flag', with loc()
#Setting up criteria - Low spender < 10
ords_prods_merge.loc[ords_prods_merge['Avg_spending'] < 10, 'spending_flag'] = 'Low spender'

In [51]:
#Checking the frequency of the new column in the dataframe 'ords_prods_merge'
ords_prods_merge['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     32285150
High spender      119709
Name: count, dtype: int64

In [52]:
#Checking the dimention of the dataframe 'ords_prods_merge'
ords_prods_merge.shape

(32404859, 22)

In [53]:
#Checking the dataframe based on the new coumn
ords_prods_merge[['user_id', 'loyalty_flag', 'spending_flag', 'Avg_spending']].head(60)

    user_id      loyalty_flag spending_flag  Avg_spending
0       138  Regular customer   Low spender      6.935811
1       138  Regular customer   Low spender      6.935811
2       709      New customer   Low spender      7.930208
3       764      New customer   Low spender      4.972414
4       764      New customer   Low spender      4.972414
5       777  Regular customer   Low spender      6.935398
6       825      New customer   Low spender      5.957576
7       910  Regular customer   Low spender      6.680000
8      1052  Regular customer   Low spender      7.162500
9      1052  Regular customer   Low spender      7.162500
10     1379      New customer   Low spender      5.813636
11     1480    Loyal customer   Low spender      5.081633
12     1480    Loyal customer   Low spender      5.081633
13     1480    Loyal customer   Low spender      5.081633
14     1494  Regular customer   Low spender      6.803797
15     1494  Regular customer   Low spender      6.803797
16     1494  Regular customer   Low spender      6.803797
17     1540  Regular customer   Low spender      6.607122
18     1540  Regular customer   Low spender      6.607122
19     1540  Regular customer   Low spender      6.607122
20     1540  Regular customer   Low spender      6.607122
21     1540  Regular customer   Low spender      6.607122
22     1540  Regular customer   Low spender      6.607122
23     1540  Regular customer   Low spender      6.607122
24     1540  Regular customer   Low spender      6.607122
25     1540  Regular customer   Low spender      6.607122
26     1540  Regular customer   Low spender      6.607122
27     1540  Regular customer   Low spender      6.607122
28     1540  Regular customer   Low spender      6.607122
29     1540  Regular customer   Low spender      6.607122
30     1540  Regular customer   Low spender      6.607122
31     1540  Regular customer   Low spender      6.607122
32     1540  Regular customer   Low spender      6.607122
33     1540  Regular customer   Low spender      6.607122
34     1598      New customer   Low spender      7.123529
35     1598      New customer   Low spender      7.123529
36     1598      New customer   Low spender      7.123529
37     1647      New customer   Low spender      4.853521
38     1647      New customer   Low spender      4.853521
39     1647      New customer   Low spender      4.853521
40     1647      New customer   Low spender      4.853521
41     1647      New customer   Low spender      4.853521
42     2833      New customer   Low spender      7.377143
43     2850  Regular customer   Low spender      8.054153
44     2857  Regular customer   Low spender      8.353793
45     3010  Regular customer   Low spender      6.452800
46     3029      New customer   Low spender      7.960606
47     3395      New customer   Low spender      6.322222
48     3904      New customer   Low spender      7.511111
49     4006    Loyal customer   Low spender      7.441100
50     4006    Loyal customer   Low spender      7.441100
51     4006    Loyal customer   Low spender      7.441100
52     4006    Loyal customer   Low spender      7.441100
53     4006    Loyal customer   Low spender      7.441100
54     4122  Regular customer   Low spender      7.598765
55     4141      New customer   Low spender      6.033333
56     4343      New customer   Low spender      7.393939
57     4553      New customer   Low spender      5.715789
58     4845  Regular customer   Low spender      7.229630
59     6866      New customer   Low spender      4.807143

In [54]:
#Checking the frequency of spending habits based on loyalty status.
ords_prods_merge.groupby('loyalty_flag')['spending_flag'].value_counts()

loyalty_flag      spending_flag
Loyal customer    Low spender      10270197
                  High spender        13896
New customer      Low spender       6185362
                  High spender        58628
Regular customer  Low spender      15829591
                  High spender        47185
Name: count, dtype: int64

# Observation 6. 

##### Checking the frequency of the spending
##### Created a new column named 'Avg_spending'
##### Splitting the data into groups based on the 'user_id' column
##### Applying the transform() function on the 'prices' column to calculate the average amount spent by each user
##### Creating a new column named 'Avg_spending' to store the results of the aggregation


##### Created 'spending_flag' based on the average amount spent per customer. 
##### If a customer spends more than or equal to 10, they are classified as a high spender. 
##### If a customer spends less than 10, they are classified as a low spender."


##### We can see that there are more'low spender' customers than 'high spender' customers. 
##### When considering the frequency of spending habits based on loyalty status: the "Loyal customers" do not necessarily drive sales in Instacart. 
##### Highest spenders: 'new customers', followed by 'regular customers', and then 'loyal customers'. 
##### Lowest spenders: 'regular spenders', followed by 'loyal customers', and then 'new customers'.

##### Total dataframe ords_prods_merge 32404859 rows X 22 columns

In [56]:
pd.options.display.max_columns = None

In [57]:
#Checking the dataframe 'ords_prods_merge'
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,Avg_spending,spending_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811,Low spender
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811,Low spender
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender

In [58]:
#Apply the transform () funtion on the 'days_since_prior_order' column to generate the median 'days_since_prior_order' for each user
#Assign the results in a new column names 'median_days_since_last_order'
ords_prods_merge['median_days_since_last_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

/var/folders/62/xltcnc5n7d97j6t5ql_87vym0000gn/T/ipykernel_14577/2339524792.py:3: FutureWarning: The provided callable <function median at 0x10621f100> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['median_days_since_last_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [59]:
#Checking the dataframe 'ords_prods_merge'
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,Avg_spending,spending_flag,median_days_since_last_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811,Low spender,8.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811,Low spender,8.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,9.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,9.0

In [60]:
#Deriving anew column named 'order_frquency_flag', with loc()
#Setting up criteria - 'Non-frequent customer' > 20
ords_prods_merge.loc[ords_prods_merge['median_days_since_last_order'] > 20, 'order_frquency_flag'] = 'Non-frequent customer'

In [61]:
#Deriving anew column named 'order_frquency_flag', with loc()
#Setting up criteria - 'Regular customer' <= 20 &  > 10
ords_prods_merge.loc[(ords_prods_merge['median_days_since_last_order'] <= 20) & (ords_prods_merge['median_days_since_last_order'] > 10), 'order_frquency_flag'] = 'Regular customer'

In [62]:
#Deriving anew column named 'order_frquency_flag', with loc()
#Setting up criteria - 'Frequent customer' <= 10
ords_prods_merge.loc[ords_prods_merge['median_days_since_last_order'] <= 10, 'order_frquency_flag'] = 'Frequent customer'

In [63]:
#Checking the frequency of the new column in the dataframe 'ords_prods_merge'
ords_prods_merge['order_frquency_flag'].value_counts(dropna = False)

order_frquency_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: count, dtype: int64

In [64]:
#Checking the dimention of the dataframe 'ords_prods_merge'
ords_prods_merge.shape

(32404859, 24)

In [65]:
#Checking the dataframe based on the new coumn
ords_prods_merge[['user_id', 'loyalty_flag', 'spending_flag', 'order_frquency_flag', 'median_days_since_last_order']].head(60)

,user_id,loyalty_flag,spending_flag,order_frquency_flag,median_days_since_last_order
0,138,Regular customer,Low spender,Frequent customer,8.0
1,138,Regular customer,Low spender,Frequent customer,8.0
2,709,New customer,Low spender,Frequent customer,8.0
3,764,New customer,Low spender,Frequent customer,9.0
4,764,New customer,Low spender,Frequent customer,9.0
5,777,Regular customer,Low spender,Regular customer,11.0
6,825,New customer,Low spender,Regular customer,20.0
7,910,Regular customer,Low spender,Frequent customer,6.0
8,1052,Regular customer,Low spender,Frequent customer,10.0
9,1052,Regular customer,Low spender,Frequent customer,10.0
10,1379,New customer,Low spender,Regular customer,20.0
11,1480,Loyal customer,Low spender,Frequent customer,7.0
12,1480,Loyal customer,Low spender,Frequent customer,7.0
13,1480,Loyal customer,Low spender,Frequent customer,7.0
14,1494,Regular customer,Low spender,Frequent customer,7.0
15,1494,Regular customer,Low spender,Frequent customer,7.0
16,1494,Regular customer,Low spender,Frequent customer,7.0
17,1540,Regular customer,Low spender,Frequent customer,7.0
18,1540,Regular customer,Low spender,Frequent customer,7.0
19,1540,Regular customer,Low spender,Frequent customer,7.0
20,1540,Regular customer,Low spender,Frequent customer,7.0
21,1540,Regular customer,Low spender,Frequent customer,7.0
22,1540,Regular customer,Low spender,Frequent customer,7.0
23,1540,Regular customer,Low spender,Frequent customer,7.0
24,1540,Regular customer,Low spender,Frequent customer,7.0
25,1540,Regular customer,Low spender,Frequent customer,7.0
26,1540,Regular customer,Low spender,Frequent customer,7.0
27,1540,Regular customer,Low spender,Frequent customer,7.0
28,1540,Regular customer,Low spender,Frequent customer,7.0
29,1540,Regular customer,Low spender,Frequent customer,7.0
30,1540,Regular customer,Low spender,Frequent customer,7.0
31,1540,Regular customer,Low spender,Frequent customer,7.0
32,1540,Regular customer,Low spender,Frequent customer,7.0
33,1540,Regular customer,Low spender,Frequent customer,7.0
34,1598,New customer,Low spender,Frequent customer,2.0
35,1598,New customer,Low spender,Frequent customer,2.0
36,1598,New customer,Low spender,Frequent customer,2.0
37,1647,New customer,Low spender,Non-frequent customer,25.0
38,1647,New customer,Low spender,Non-frequent customer,25.0
39,1647,New customer,Low spender,Non-frequent customer,25.0
40,1647,New customer,Low spender,Non-frequent customer,25.0
41,1647,New customer,Low spender,Non-frequent customer,25.0
42,2833,New customer,Low spender,Regular customer,13.0
43,2850,Regular customer,Low spender,Frequent customer,7.0
44,2857,Regular customer,Low spender,Regular customer,11.0
45,3010,Regular customer,Low spender,Frequent customer,7.0
46,3029,New customer,Low spender,Non-frequent customer,28.0
47,3395,New customer,Low spender,Regular customer,18.0
48,3904,New customer,Low spender,Non-frequent customer,21.0
49,4006,Loyal customer,Low spender,Frequent customer,7.0
50,4006,Loyal customer,Low spender,Frequent customer,7.0
51,4006,Loyal customer,Low spender,Frequent customer,7.0
52,4006,Loyal customer,Low spender,Frequent customer,7.0
53,4006,Loyal customer,Low spender,Frequent customer,7.0
54,4122,Regular customer,Low spender,Frequent customer,7.0
55,4141,New customer,Low spender,Non-frequent customer,30.0
56,4343,New customer,Low spender,Non-frequent customer,30.0
57,4553,New customer,Low spender,Non-frequent customer,30.0
58,4845,Regular customer,Low spender,Regular customer,20.0
59,6866,New customer,Low spender,Non-frequent customer,30.0

In [66]:
#Checking the order frequency based on spending status.
ords_prods_merge.groupby('spending_flag')['order_frquency_flag'].value_counts()

spending_flag  order_frquency_flag
High spender   Frequent customer           56944
               Regular customer            33234
               Non-frequent customer       29531
Low spender    Frequent customer        21502909
               Regular customer          7175330
               Non-frequent customer     3606906
Name: count, dtype: int64

# Observation 7. 

##### Checking the frequency of the spending


##### Checking the frequency of days since placing the last order.
##### Created a new column named 'median_days_since_last_order'
##### Splitting the data into groups based on the 'user_id' column
##### Applying the transform() function on the 'days_since_prior_order' column to calculate the median days since the last order by each user
##### Creating a new column named 'median_days_since_last_order' to store the results of the aggregation


##### Created 'order_frquency_flag' based on the 'median_days_since_last_order' per customer. 
##### If a customer 'median_days_since_last_order',  > 20, they are classified as 'Non-frequent customer'. 
##### If a customer 'median_days_since_last_order', <= 20 & > 10, they are classified as 'Regular customer'. 
##### If a customer 'median_days_since_last_order', <= 10, they are classified as 'Frequent customer'. 

##### We can see that there are more'Frequent customer' customers than other customers. 
##### The results also show 'NaN' where there is no available data for the very first order placed by the customers.
##### When considering the order frequency based on spending status: the "High spender" do not necessarily placing frequent orders in Instacart. 
##### Lower spender customers are 'Frequent customer' compared to High spender customers.

##### Total dataframe ords_prods_merge 32404859 rows X 24 columns.

In [68]:
# Export the 'ords_prods_merge_agg' dataframe to pkl formate
ords_prods_merge.to_pickle(os.path.join(path, '02-Data','Prepared-Data', 'ords_prods_merge_agg.pkl'))

### Observation 9.
##### Export the grouped and aggregated data in pickle format as “ords_prods_merge_agg.pkl”